import { expect, test } from '@playwright/test'

const pages = [['/#/collections', 'Colecciones'], ['/#/profiles', 'Perfiles y actividades'], ['/#/settings', 'Configuración'], ['/#/official-sources', 'Fuentes oficiales'], ['/#/library', 'Biblioteca local']] as const

test('muestra contador real, grupos operativos y conserva historial al limpiar', async ({ page }) => {
  await page.goto('/#/collections')
  await expect(page.getByText('99+', { exact: true })).toBeVisible()
  const jobs = page.getByRole('button', { name: /Abrir centro de ejecuciones: 101 sin leer/ })
  await expect(jobs).toBeVisible(); await jobs.click()
  await expect(page.getByRole('heading', { name: 'Centro de ejecuciones' })).toBeVisible()
  await expect(page.getByText('En curso', { exact: true })).toBeVisible()
  await expect(page.getByText('Requieren atención', { exact: true })).toBeVisible()
  await expect(page.getByText('Finalizadas sin leer', { exact: true })).toBeVisible()
  const beforeClear = await page.evaluate(async () => fetch('/api/v1/runs').then((response) => response.json())) as { items: Array<{ status: string; readAt: string | null }> }
  expect(beforeClear.items).toHaveLength(101)
  expect(beforeClear.items.filter((run) => run.status === 'completed' || run.status === 'failed').every((run) => run.readAt === null)).toBeTruthy()
  await page.getByRole('button', { name: 'Limpiar finalizadas' }).click()
  await page.reload()
  const afterClear = await page.evaluate(async () => fetch('/api/v1/runs').then((response) => response.json())) as { items: Array<{ status: string; readAt: string | null }> }
  expect(afterClear.items).toHaveLength(101)
  expect(afterClear.items.filter((run) => run.status === 'completed' || run.status === 'failed').every((run) => run.readAt !== null)).toBeTruthy()
  expect(afterClear.items.filter((run) => run.status === 'queued' || run.status === 'running' || run.status === 'blocked').every((run) => run.readAt === null)).toBeTruthy()
  const reduced = page.getByRole('button', { name: /Abrir centro de ejecuciones: 3 sin leer/ })
  await expect(reduced).toBeVisible(); await reduced.click()
  await expect(page.getByText('En curso', { exact: true })).toBeVisible()
  await expect(page.getByText('Requieren atención', { exact: true })).toBeVisible()
})

test('aísla el historial Alfa y abre factura analizada o pendiente sin inferir resultados', async ({ page }) => {
  await page.goto('/#/collections')
  await page.getByRole('button', { name: 'Abrir colección Colección Alfa' }).click()
  await page.getByRole('button', { name: 'Historial' }).click()
  await expect(page.getByRole('heading', { name: 'Historial de colección' })).toBeVisible()
  await expect(page.getByText('Colección Beta', { exact: true })).not.toBeVisible()
  await page.waitForTimeout(5500)
  await expect(page.getByText('Colección Beta', { exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: 'Abrir Ejecución local' }).last().click()
  await expect(page.getByRole('heading', { name: 'Detalle de ejecución local' })).toBeVisible()
  await expect(page.getByText('Eventos', { exact: true })).toBeVisible()
  await expect(page.getByText(/Resultado sintético para comprobar/)).not.toBeVisible()
  await page.getByRole('button', { name: 'Abrir resultado de factura' }).click()
  await expect(page.getByRole('heading', { name: 'Detalle de factura' })).toBeVisible()
  await expect(page.getByText('Proveedor sintético S.A.')).toBeVisible()
  await expect(page.getByText('Resultado de la factura analizada')).toBeVisible()
  await page.getByRole('button', { name: 'Volver a la ejecución' }).click()
  await page.getByRole('button', { name: 'Volver al listado' }).click()
  await page.getByRole('button', { name: 'Cerrar ejecuciones locales' }).click()
  await page.getByRole('button', { name: 'Volver a colecciones' }).click()
  await page.getByRole('button', { name: 'Abrir colección Colección Beta' }).click()
  await page.locator('tr').filter({ hasText: 'factura-compartida.xml' }).getByRole('button', { name: 'Ver detalle' }).click()
  await expect(page.getByText('Sin análisis todavía')).toBeVisible()
  await expect(page.getByText('Resultado de la factura analizada')).not.toBeVisible()
  await page.getByRole('button', { name: 'Cerrar ejecuciones locales' }).click()
  await page.locator('tr').filter({ hasText: 'factura-pendiente.xml' }).getByRole('button', { name: 'Ver detalle' }).click()
  await expect(page.getByText('Sin análisis todavía')).toBeVisible()
  await page.getByRole('tab', { name: 'Datos' }).click()
  await expect(page.getByText('Servicio sintético local')).toBeVisible()
  await expect(page.getByText('2 · 15')).toBeVisible()
  await expect(page.getByRole('cell', { name: '$100,00' }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar ejecuciones locales' }).click()
  await page.getByRole('button', { name: 'Ver detalle' }).first().click()
  await expect(page.getByText('Sin análisis todavía')).toBeVisible()
})

test('permite alcanzar la columna total de factura en 320 px sin desbordar la raíz', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await page.goto('/#/collections')
  await page.getByRole('button', { name: 'Abrir colección Colección Alfa' }).click()
  await page.locator('tr').filter({ hasText: 'factura-compartida.xml' }).getByRole('button', { name: 'Ver detalle' }).click()
  await page.getByRole('tab', { name: 'Datos' }).click()
  const totalCell = page.getByRole('cell', { name: '$100,00' }).last()
  await totalCell.scrollIntoViewIfNeeded()
  await expect(totalCell).toBeVisible()
  const reachable = await totalCell.boundingBox()
  expect(reachable?.x).toBeGreaterThanOrEqual(0)
  expect((reachable?.x ?? 0) + (reachable?.width ?? 0)).toBeLessThanOrEqual(321)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
})

test('mantiene la altura del sondeo local con una respuesta HTTP sintética', async ({ page }, testInfo) => {
  await page.goto('/#/collections')
  await page.getByRole('button', { name: 'Abrir colección Colección Alfa' }).click()
  await page.getByRole('button', { name: 'Analizar colección' }).click()
  const dialog = page.getByRole('dialog', { name: 'Analizar colección' })
  await expect(dialog).toBeVisible()
  const before = await dialog.boundingBox()
  await page.route('**/api/v1/connections/*/probe', async (route) => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ ok: true, message: 'Conexión sintética validada.' }) }))
  await dialog.getByRole('button', { name: 'Probar conexión' }).click()
  await expect(dialog.getByRole('status')).toContainText('Conexión sintética validada.')
  const after = await dialog.boundingBox()
  expect(Math.abs((before?.height ?? 0) - (after?.height ?? 0))).toBeLessThan(1)
  const probeButton = dialog.getByRole('button', { name: 'Probar conexión' })
  const probeBox = await probeButton.boundingBox()
  expect(probeBox?.x).toBeGreaterThanOrEqual(0)
  await page.screenshot({ path: testInfo.outputPath('analysis-probe-synthetic.png'), fullPage: true })
})

test('mantiene páginas y overlays accesibles en anchos compactos y ambos temas', async ({ page }, testInfo) => {
  test.setTimeout(90_000)
  for (const color of ['light', 'dark'] as const) for (const width of [320, 375, 414, 768, 1280]) {
    await page.setViewportSize({ width, height: 720 }); await page.goto('/#/collections')
    await page.evaluate((nextColor) => localStorage.setItem('mantine-color-scheme-value', nextColor), color)
    await page.reload()
    await expect(page.locator('html')).toHaveAttribute('data-mantine-color-scheme', color)
    for (const [path, heading] of pages) {
      await page.goto(path); await expect(page.getByRole('heading', { name: heading }).first()).toBeVisible()
      await expect(page.locator('h1')).toHaveCount(1)
      const buttons = page.getByRole('button')
      for (let index = 0; index < await buttons.count(); index += 1) {
        await buttons.nth(index).scrollIntoViewIfNeeded()
        const box = await buttons.nth(index).boundingBox()
        if (box) { expect(box.x).toBeGreaterThanOrEqual(0); expect(box.x + box.width).toBeLessThanOrEqual(width + 1) }
      }
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
      await page.evaluate(() => window.scrollTo(0, 0))
      await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => resolve())))
      await page.screenshot({ path: testInfo.outputPath(`${heading}-${color}-${width}.png`), fullPage: true })
    }
    await page.goto('/#/collections'); await page.getByRole('button', { name: 'Nueva colección' }).click()
    await expect(page.getByRole('heading', { name: 'Nueva colección local' })).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath(`modal-collection-open-${color}-${width}.png`), fullPage: true })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('heading', { name: 'Nueva colección local' })).not.toBeVisible()
    await expect(page.getByRole('button', { name: 'Nueva colección' })).toBeFocused()
    await page.getByRole('button', { name: 'Abrir colección Colección Alfa' }).click()
    await expect(page.getByRole('heading', { name: 'Colección Alfa' })).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath(`collection-detail-${color}-${width}.png`), fullPage: true })
    await page.route('**/api/v1/connections/*/probe', async (route) => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ ok: true, message: 'Conexión sintética validada.' }) }))
    await page.getByRole('button', { name: 'Analizar colección' }).click()
    const analysis = page.getByRole('dialog', { name: 'Analizar colección' })
    const beforeProbe = await analysis.boundingBox()
    await page.screenshot({ path: testInfo.outputPath(`analysis-before-probe-${color}-${width}.png`), fullPage: true })
    await analysis.getByRole('button', { name: 'Probar conexión' }).click()
    await expect(analysis.getByRole('status')).toContainText('Conexión sintética validada.')
    const afterProbe = await analysis.boundingBox()
    expect(Math.abs((beforeProbe?.height ?? 0) - (afterProbe?.height ?? 0))).toBeLessThan(1)
    const probe = await analysis.getByRole('button', { name: 'Probar conexión' }).boundingBox()
    expect(probe?.x).toBeGreaterThanOrEqual(0)
    await page.screenshot({ path: testInfo.outputPath(`analysis-after-probe-${color}-${width}.png`), fullPage: true })
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Historial' }).click()
    const runDrawer = page.getByRole('dialog', { name: 'Historial de colección' })
    await expect(runDrawer).toBeVisible()
    await expect.poll(async () => { const box = await runDrawer.boundingBox(); return box ? box.x >= 0 && box.x + box.width <= width : false }).toBeTruthy()
    await page.screenshot({ path: testInfo.outputPath(`run-drawer-${color}-${width}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Abrir Ejecución local' }).last().click()
    const detailDrawer = page.getByRole('dialog', { name: 'Detalle de ejecución local' })
    await expect(detailDrawer).toBeVisible()
    await expect.poll(async () => { const box = await detailDrawer.boundingBox(); return box ? box.x >= 0 && box.x + box.width <= width : false }).toBeTruthy()
    await page.screenshot({ path: testInfo.outputPath(`run-detail-drawer-${color}-${width}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Abrir resultado de factura' }).click()
    const invoiceDrawer = page.getByRole('dialog', { name: 'Detalle de factura' })
    await expect(invoiceDrawer).toBeVisible()
    await expect.poll(async () => { const box = await invoiceDrawer.boundingBox(); return box ? box.x >= 0 && box.x + box.width <= width : false }).toBeTruthy()
    await page.screenshot({ path: testInfo.outputPath(`invoice-drawer-${color}-${width}.png`), fullPage: true })
    await page.keyboard.press('Escape')
  }
})
