/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicSignUpRouteImport } from './routes/(public)/sign-up'
import { Route as publicSignInRouteImport } from './routes/(public)/sign-in'
import { Route as publicForgotPasswordRouteImport } from './routes/(public)/forgot-password'
import { Route as privateUserRouteImport } from './routes/(private)/user'
import { Route as privateProfilesRouteImport } from './routes/(private)/profiles'
import { Route as privateOfficialSourcesRouteImport } from './routes/(private)/official-sources'
import { Route as privateAccountRouteImport } from './routes/(private)/account'
import { Route as privateJobsIndexRouteImport } from './routes/(private)/jobs/index'
import { Route as privateCollectionsIndexRouteImport } from './routes/(private)/collections/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as privateCollectionsIdRouteImport } from './routes/(private)/collections/$id'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicForgotPasswordRoute = publicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => publicRouteRoute,
} as any)
const privateUserRoute = privateUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateProfilesRoute = privateProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateOfficialSourcesRoute = privateOfficialSourcesRouteImport.update({
  id: '/official-sources',
  path: '/official-sources',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateAccountRoute = privateAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateJobsIndexRoute = privateJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateCollectionsIndexRoute = privateCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => privateRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privateCollectionsIdRoute = privateCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => privateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/account': typeof privateAccountRoute
  '/official-sources': typeof privateOfficialSourcesRoute
  '/profiles': typeof privateProfilesRoute
  '/user': typeof privateUserRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/': typeof publicIndexRoute
  '/collections/$id': typeof privateCollectionsIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/collections/': typeof privateCollectionsIndexRoute
  '/jobs/': typeof privateJobsIndexRoute
}
export interface FileRoutesByTo {
  '/account': typeof privateAccountRoute
  '/official-sources': typeof privateOfficialSourcesRoute
  '/profiles': typeof privateProfilesRoute
  '/user': typeof privateUserRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/': typeof publicIndexRoute
  '/collections/$id': typeof privateCollectionsIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/collections': typeof privateCollectionsIndexRoute
  '/jobs': typeof privateJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(private)/account': typeof privateAccountRoute
  '/(private)/official-sources': typeof privateOfficialSourcesRoute
  '/(private)/profiles': typeof privateProfilesRoute
  '/(private)/user': typeof privateUserRoute
  '/(public)/forgot-password': typeof publicForgotPasswordRoute
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/(public)/': typeof publicIndexRoute
  '/(private)/collections/$id': typeof privateCollectionsIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/(private)/collections/': typeof privateCollectionsIndexRoute
  '/(private)/jobs/': typeof privateJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account'
    | '/official-sources'
    | '/profiles'
    | '/user'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/collections/$id'
    | '/api/trpc/$'
    | '/collections/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/official-sources'
    | '/profiles'
    | '/user'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/collections/$id'
    | '/api/trpc/$'
    | '/collections'
    | '/jobs'
  id:
    | '__root__'
    | '/(private)'
    | '/(public)'
    | '/(private)/account'
    | '/(private)/official-sources'
    | '/(private)/profiles'
    | '/(private)/user'
    | '/(public)/forgot-password'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
    | '/(public)/'
    | '/(private)/collections/$id'
    | '/api/trpc/$'
    | '/(private)/collections/'
    | '/(private)/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/forgot-password': {
      id: '/(public)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicForgotPasswordRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(private)/user': {
      id: '/(private)/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof privateUserRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/profiles': {
      id: '/(private)/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof privateProfilesRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/official-sources': {
      id: '/(private)/official-sources'
      path: '/official-sources'
      fullPath: '/official-sources'
      preLoaderRoute: typeof privateOfficialSourcesRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/account': {
      id: '/(private)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof privateAccountRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/jobs/': {
      id: '/(private)/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof privateJobsIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/collections/': {
      id: '/(private)/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof privateCollectionsIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/collections/$id': {
      id: '/(private)/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof privateCollectionsIdRouteImport
      parentRoute: typeof privateRouteRoute
    }
  }
}

interface privateRouteRouteChildren {
  privateAccountRoute: typeof privateAccountRoute
  privateOfficialSourcesRoute: typeof privateOfficialSourcesRoute
  privateProfilesRoute: typeof privateProfilesRoute
  privateUserRoute: typeof privateUserRoute
  privateCollectionsIdRoute: typeof privateCollectionsIdRoute
  privateCollectionsIndexRoute: typeof privateCollectionsIndexRoute
  privateJobsIndexRoute: typeof privateJobsIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateAccountRoute: privateAccountRoute,
  privateOfficialSourcesRoute: privateOfficialSourcesRoute,
  privateProfilesRoute: privateProfilesRoute,
  privateUserRoute: privateUserRoute,
  privateCollectionsIdRoute: privateCollectionsIdRoute,
  privateCollectionsIndexRoute: privateCollectionsIndexRoute,
  privateJobsIndexRoute: privateJobsIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicForgotPasswordRoute: typeof publicForgotPasswordRoute
  publicSignInRoute: typeof publicSignInRoute
  publicSignUpRoute: typeof publicSignUpRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicForgotPasswordRoute: publicForgotPasswordRoute,
  publicSignInRoute: publicSignInRoute,
  publicSignUpRoute: publicSignUpRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
