/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicSignUpRouteImport } from './routes/(public)/sign-up'
import { Route as privateUserRouteImport } from './routes/(private)/user'
import { Route as privateJobsIndexRouteImport } from './routes/(private)/jobs/index'
import { Route as privateCollectionsIndexRouteImport } from './routes/(private)/collections/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as privateCollectionsIdRouteImport } from './routes/(private)/collections/$id'

const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/(public)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const privateUserRoute = privateUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateJobsIndexRoute = privateJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateCollectionsIndexRoute = privateCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => privateRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privateCollectionsIdRoute = privateCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => privateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/user': typeof privateUserRoute
  '/sign-up': typeof publicSignUpRoute
  '/': typeof publicIndexRoute
  '/collections/$id': typeof privateCollectionsIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/collections/': typeof privateCollectionsIndexRoute
  '/jobs/': typeof privateJobsIndexRoute
}
export interface FileRoutesByTo {
  '/user': typeof privateUserRoute
  '/sign-up': typeof publicSignUpRoute
  '/': typeof publicIndexRoute
  '/collections/$id': typeof privateCollectionsIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/collections': typeof privateCollectionsIndexRoute
  '/jobs': typeof privateJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/(private)/user': typeof privateUserRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/(public)/': typeof publicIndexRoute
  '/(private)/collections/$id': typeof privateCollectionsIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/(private)/collections/': typeof privateCollectionsIndexRoute
  '/(private)/jobs/': typeof privateJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/user'
    | '/sign-up'
    | '/'
    | '/collections/$id'
    | '/api/trpc/$'
    | '/collections/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/user'
    | '/sign-up'
    | '/'
    | '/collections/$id'
    | '/api/trpc/$'
    | '/collections'
    | '/jobs'
  id:
    | '__root__'
    | '/(private)'
    | '/(private)/user'
    | '/(public)/sign-up'
    | '/(public)/'
    | '/(private)/collections/$id'
    | '/api/trpc/$'
    | '/(private)/collections/'
    | '/(private)/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicSignUpRoute: typeof publicSignUpRoute
  publicIndexRoute: typeof publicIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/user': {
      id: '/(private)/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof privateUserRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/jobs/': {
      id: '/(private)/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof privateJobsIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/collections/': {
      id: '/(private)/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof privateCollectionsIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/collections/$id': {
      id: '/(private)/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof privateCollectionsIdRouteImport
      parentRoute: typeof privateRouteRoute
    }
  }
}

interface privateRouteRouteChildren {
  privateUserRoute: typeof privateUserRoute
  privateCollectionsIdRoute: typeof privateCollectionsIdRoute
  privateCollectionsIndexRoute: typeof privateCollectionsIndexRoute
  privateJobsIndexRoute: typeof privateJobsIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateUserRoute: privateUserRoute,
  privateCollectionsIdRoute: privateCollectionsIdRoute,
  privateCollectionsIndexRoute: privateCollectionsIndexRoute,
  privateJobsIndexRoute: privateJobsIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  publicSignUpRoute: publicSignUpRoute,
  publicIndexRoute: publicIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
